---
output: github_document
resource_files:
  vignettes/mapspam.bib
bibliography: vignettes/bib/mapspam.bib

---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# mapspam2globiom

<!-- badges: start -->
<!-- badges: end -->

The aim of the mapspam2globiom R package is to facilitate the creation of country level crop distribution maps, which can be used as input by the IIASA's [Global Biosphere Management Model (GLOBIOM)](https://www.globiom.org/). GLOBIOM is a spatially explicit partial equilibrium model that is used to analyze the competition for land use between agriculture, forestry, and bioenergy. The model can be used for global and national level analysis [@Valin2013b; @Leclere2014; @Havlik2014; @Soterroni2018]. In the latter case, model output can be greatly improved by incorporating regionally specific information that is often provided by local stakeholders or can be taken from national statistics. Information on crop cover and the location of crops are a key driver of the model and it is therefore desirable to base these as much as possible on national sources of information. 

mapspam2globiom provides the necessary infrastructure to run the Spatial Production Allocation Model for Country level studies (SPAMc). The model builds on the global version of SPAM [@You2006; @You2009; @You2014a; @Yu2020], which use an cross-entropy optimization approach to 'pixelate' national and subnational crop statistics on a spatial grid at a 5 arcmin resolution. SPAMc was specifically developed to support country level analysis and makes it possible to incorporate national sources of information and create maps at a higher resolution of 30 arcsec [@VanDijk2020]. The articles in the Background section provide more information on the model, including [model structure](articles/model_structure.html), overview of [input data](articles/data.html) and an [appendix](articles/appendix.html) with the equations. Apart from implementing SPAMc, mapspam2globiom includes functions to aggregate the SPAMc output to the spatial (i.e. simulation units) and crop-level (18 major crops) format that is used by GLOBIOM.


## Installation

To install mapspam2globiom:

``` r
install.packages("remotes")
remotes::install_github("iiasa/mapspam2globiom")
```
Apart from the mapspam2globiom package, several other pieces of software are essential to run SPAMc, which are described in the [Installation](articles/software.html) section.

## Preparation

It takes some preparation before SPAMc can be run. Most important and propbably most time consuming is the collection of input data. SPAMc is a data-driven model and therefore requires a large variety of input data, which can be grouped under two headers: (1) (Sub)national agricultural statistics and (2) spatial information. The availability of data strongly affects the structure of the model and how can be solved. Hence, we highly recommend to start collecting input data before running the model. The articles in the Preparation section give an overview of all the information that is requited by SPAMc and shows were to download templates/examples that can be used as a framework to apply SPAMc to other countries:

- [Input data collection](articles/collect_input_data.html).
- [Download templates](articles/template.html)


## Run SPAMc

Running SPAMc can be divided into seven steps, which are described in the articles in the Run SPAMc section:

- [Model setup](articles/model_structure.html)
- [Processing of subnational statistics](articles/process_subnat_stat.html)
- [Processing of spatial data](articles/process_spatial_data.html)
- Create cropland extent
- Create irrigated area extend
- [Run model](articles/run_model.html)
- [Post-processing](articles/post_process.html)


## References
