---
title: "appendix_b"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{appendix_b}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Storage and formats of model input and output

Depending on the resolution of the model and the size of the country, the size of the input (raw and processed) and output files can become quite large. Hence it is important to ensure sufficient disk space to store the files. To give you an idea, all files related to the China example have a total size of [@ADD], while the total size for the Malawi example is [@ADD]. We also encountered some problems when performing some of the GDAL operations using DropBox, probably related to the  synchronization of files. If you encounter problems when saving to Dropbox, try saving to a folder that is not being  synchronizated automatically.  

In most cases we use the following file formats to store data:
- Raster maps are stored using Geotiff (*.tif).
- Shape files (i.e. vector/polygon data) are stored in the R .rds data format, which ensures the data structure is maintained and data can be quickly loaded into R. The shapefile with ADM information is also saved in .shp format as this is needed for GDAL.
- Data files are stored in the R .rds data format. For files with lists of information (e.g. list of crops and ADMs in the country) we use .csv files for quick referencing (e.g. using Excel).
- GAMS code is saved in .gms [@UPDATE]
- GAMS data files are stored in .gdx [@UPDATE]

