---
title: "Create synergy cropland map"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create synergy cropland map}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

A key feature of SPAMc is to allocate the crop statistics to areas identified as cropland on a map - the cropland extent. As described in the section on [Input data](data.html), we use a so-called synergy cropland map to account for the uncertainty in the location of cropland. The synergy cropland map combines different cropland products to construct one map that presents the mean and maximum available crop area per grid cell as well as a ranking that measures the agreement between the various cropland products. A ranking of 1 means that all sources agree there is cropland in a grid cell, while higher rankings signals more disagreement. The highest ranking depends on the number of cropland products that are compared. 

@TODO add illustration how to make a synergy cropland map.


For 2010, we can make use of SASAM, the global synergy map that was prepared for SPAM2010 [@Lu2020].  

