---
title: "Input data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Input data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
resource_files:
  bib/mapspam.bib
bibliography: bib/mapspam.bib
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Crop statistics

Information on harvested area by crop at the subnational level is of key importance and greatly improves the quality of the gridded maps [@Joglekar2019]. Our main source of information was the global databases with subnational agricultural statistics that were prepared to inform the the Spatial Production Allocation Model (SPAM, www.mapspam.info) for 2000 (SPAM2000) and 2010 (SPAM2010). The database contains production statistics (e.g. yield, harvested area and production) at three administrative area levels (ADMs): (ADM0) national level, (ADM1) state/provincial level and (ADM2) district/department level. For each year the subnational statistics were scaled to FAOSTAT average national totals using a three year average (i.e. 1999-2001 and 2009-2011) to account for annual volatility. To convert harvested area into physical area, SPAM also includes crop, country and farming system specific information on cropping intensity. Detailed descriptions about the sources and construction of the database can be found in @You2014a, @Wood-Sichra2016 and @Yu2020. In a few cases, we updated the SPAM subnational agricultural statistics database with recent data from AQUASTAT [@FAO2016] on irrigated area and information derived from OpenStreetMap. 

The databases that were constructed for SPAM2000 and SPAM2010 are not always directly comparable due to (1) differences in the number of crops (and crop groups) covered - SPAM2000 includes 20 crops, while the number was expanded to 42 in SPAM2010 - and (2) changes in the boundaries and definition of the ADMs over time. Fortunately, both versions of the database distinguish between the same four farming systems (subsistence, rainfed low-input, rainfed high-input and irrigated). 

To construct a consistent dataset with subnational statistics that can be compared over time, we started by harmonizing the crop definitions for SPAM2000 and SPAM2010, using the most recent version of the database as basis. 13 out of the 20 crops in SPAM2000 could be directly linked to crop information in SPAM2010, 4 crops could be split in to more detailed crops and for 3 crops we used national information from FAOSTAT. Similarly, we also harmonized the definition of the ADMs over time. It appeared that for a number of countries, there was considerable change in the definition of the ADM2s while the definition of ADM1s was mostly stable. For this reason, we decided to use ADM1 statistics for the year 2000 for all countries. Table \@ref(tab:tab-adm-cov) compares the sub-national coverage for the seven South African countries and the two relevant years and Figure \@ref(fig:fig-adm) depicts the locations of the ADMs in the region.   


## Cropland extent

To allocate the physical area statistics SPAMc requires a cropland extent, which shows the location of cropland in a country for the target year. There are several global cropland products [@ADD] and often countries produce their own land cover map, which includes a cropland class. Comparison between different cropland sources, shows a lot of variation and often disagreement [@ADD]. To acount for the uncertainty in the location of cropland, @ADD combined several different products into one so-called synergy (or synergistic) cropland map. A more recent product was prepared by @Lu2020 and used as input for the construction of SPAM2010.

The synergy cropland approach combines all available (global) cropland maps and creates a ranking for each grid cell that measures the level of agreement between the products. In the SPAMc data-preparation stage, the grid cells with the least uncertainty are selected first when allocating physical area of individual crops. Apart from the ranking, the synergy cropland approach also creates maps with the medium and maximum cropland area per grid cell. The medium area product is used as the base layer by SPAMc but in case this is not sufficient to allocate all the physical area, grid cells from the maximum cropland map can be used (see [Combine input data](combine_input_data.html) for more information on how this is done).  


## Biophysical suitability and potential yield

Spatially explicit information on biophysical suitability and potential yield is taken from @IIASA2012. The International Institute for Applied Systems Analysis (IIASA) in collaboration with FAO, developed the global agro-ecological zones (GAEZ) methodology that assesses the biophysical limitations and potentials for a large number of crops across three farming systems: rainfed–low input/subsistence, rainfed–high input and Irrigated-high input. The first class is used for both the low-input and subsistence system in SPAMc. GAEZ presents spatially explicit information on the biophysical suitability (on a scale from 1 to 100) and potential yield for (in t/ha) separate for each farming system. As an example, Figure \@ref(fig:fig-gaez-suit) and Figure \@ref(fig:fig-gaez-prod) show suitability and potential yield for rainfed subsistence/low-input maize farming in the Southern African region, respectively. 


## Accessibility

In contrast to SPAM, which uses population density [@Wood-Sichra2016], we applied recently updated maps on travel time to as a proxy for accessibility. We argue that farmers that belong to the low-input, high-input and irrigated systems sell (most of) their products on the market. Hence, these systems will be located in areas that are close to the market or are close to main roads that provide easy access to markets. As a proxy for access to markets and quality of road infrastructure we used two global maps that measure accessibility to high-density urban centers as measured by travel time at a resolution of 1×1 kilometer. The first map [@Nelson2008] depicts the global road infrastructure in 2000, while second map [@Weiss2018] contains information for the year 2015. Although both maps depict travel time, they cannot be regarded as time-series because the maps were created with a different definition of a city. @Nelson2008 uses travel time to the nearest city of 50,000, while @Weiss2018 uses the urban areas in the Global Human Settlement Grid of high-density land cover to locate cities. The most recent product also different source information and includes minor roads (e.g., unpaved rural roads), which were only marginally covered by the older map. We used the 2000 and 2010 global travel time maps as indicator for accessibility for the 2000 and 2010 crop distribution maps, respectively.


## Rural population density

We used the WorldPop [@Tatem2017] database as a our primary source of information for national population density. WorldPop combines a random forest model with census data to generate a gridded prediction of population density at ~100 meter spatial resolution [@Stevens2015a]. Data is available for at a number of spatial resolutions and various years. We used the global maps at 1x1 kilometer and for the period 2000 and 2010 for our analysis. We prefer WorldPop data, over the Global Rural-Urban Mapping Project (GRUMP) population data that is used by SPAM because it is available at much higher resolution and available for multiple and more recent years. 

To identify rural population areas, and similar to SPAM, we use the urban extent from GRUMP [@CIESIN2011] due to lack of other sources. Urban areas, were identified by analyzing nighttime lights in combination with information on settlement points. Rural population was selected by removing grid cells that are located within the urban extent polygons. 


## Crop price

To calculate the potential revenue of a crop at the grid cell level, we followed the SPAM approach [@Wood-Sichra2016] and multiplied the potential yield from @IIASA2012 with crop prices from @FAO2019. Similar to harvested area information, we took the average over three years to smooth annual fluctuations. Due to problems of missing data, we used average prices for the African continent. 


## Fitness score

The constraint for the subsistence farming system and the fitness score for low-input, high-input and irrigated farming systems are constructed by combining one or more indicators for rural population density, biophysical suitability, accessibility and potential revenue, In order to make the data comparable, all indicators were scaled to between 0 and 1 using the using min-max normalization before further processing:

\begin{equation}
X^{\prime}_{ijl} =  \frac{X_{ijl}-min(X_{ijl})}{max(X_{ijl})-min(X_{ijl})}
\end{equation}

where $X_{ijl}$ is the one of the indicators to construct the fitness score, defined for each grid cell $i$, crop $j$ and farming system $l$, which is converted to $X^{\prime}_{ijl}$. 



## Irrigation

To allocate the irrigated crops, we created new irrigated area maps combining a number of products. As a main source of information, we used the Global Irrigated Areas (GIA) map [@Meier2018], which depicts irrigated areas for the world around the period 2005. The GIA combines normalized difference vegetation index (NDVI) maps, crop suitability data and information on the location of areas equipped for irrigation to create an irrigated area map with a resolution of 30 arcsec. In comparison to the Global Map of Irrigated Areas (GMIA) [@Siebert2013], which is used by SPAM, the GMIA shows 18% more irrigated area globally.

To create irrigation maps for 2000 and 2010, we combined and extended the GIA using two additional sources of information. First, we collected additional information on the location of irrigation schemes from regional irrigation surveys. @WorldBank2010 provides an in-depth analysis of irrigated areas in the Zambezi basin, which overlaps with the seven target countries of our study. For Malawi, we also added data from the National Irrigation Master Plan [@Ministryofagriculture2015], which presents geo-referenced inventory of irrigation systems in Malawi for the period around 2000-2010. Second, we compared the data from the irrigation surveys, the GIA and the GMIA with all OSM farmland polygons (i.e. including those for which we could not identify the crop and estate name). In many cases there was considerable overlap, matching an irrigation scheme and/or GIA and GMIA grid cell with an OSM polygon. On the basis of this, we made the assumption that any OSM farmland polygon that overlaps with a GIA grid cell or the location of an irrigation scheme can be considered as irrigated area. Finally, the irrigation map was created by merging the GIA with the OSM irrigated farmland polygons and overlaying the resulting map with the 2000 and 2010 synergy cropland maps to scale the cropland area to the respective years. For a few countries, the area in the irrigated area map was lower than the irrigated area in the country statistics. In these cases we decided to expand the the irrigation map by adding grid cells from the GMIA (which is much coarser than the GIA) that have at least 10% overlap with OSM polygons. If that was still not enough we added the remaining GMAI grid cells to the irrigation map.  


## References
